name: 'PKUPgen'
description: 'Generate PKUP reports and send them to email addresses or/and save them'
inputs:
  generate:
    description: 'Generate reports'
    default: 'true'
    required: false
  send-emails:
    description: 'Send emails'
    default: 'true'
    required: false
  since:
    description: 'Gen since (in format 02.01.2006)'
    default: ''
    required: false
  until:
    description: 'Gen until (in format 02.01.2006)'
    default: ''
    required: false
    
runs:
  using: "composite"
  steps:

  - name: Installing pkup-gen
    shell: bash
    run: |
      curl "https://raw.githubusercontent.com/pPrecel/pkup-gen-action/main/scripts/install-pkup-gen.sh" | sh -

  - name: Generate reports
    if: ${{ inputs.generate == 'true'  }}
    shell: bash
    run: |
      rm -rf reports

      ARGS="--config .pkupcompose.yaml --ci"

      [ ! -z "${{ inputs.since }}" ] && ARGS="$ARGS --since ${{ inputs.since }}"
      [ ! -z "${{ inputs.until }}" ] && ARGS="$ARGS --until ${{ inputs.until }}"

      bin/pkup compose ${ARGS}
  
  - name: Send emails
    if: ${{ inputs.send-emails == 'true' }}
    shell: bash
    run: |
      ARGS="--config .pkupcompose.yaml"

      [ ! -z "${{ inputs.until }}" ] && ARGS="$ARGS --timestamp ${{ inputs.until }}"

      bin/pkup send ${ARGS}
  